-- Additive catalog fields; existing names are preserved without guessing name parts.
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "firstName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "lastName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "isRider" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "isPayer" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "preferences" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "Client" SET "firstName" = "name" WHERE "firstName" = '';

ALTER TABLE "Horse" ADD COLUMN IF NOT EXISTS "breed" TEXT;
ALTER TABLE "Horse" ADD COLUMN IF NOT EXISTS "riderLevel" TEXT;
ALTER TABLE "Horse" ADD COLUMN IF NOT EXISTS "isUnavailable" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Trainer" ADD COLUMN IF NOT EXISTS "qualification" TEXT;
ALTER TABLE "Trainer" ADD COLUMN IF NOT EXISTS "maxDailyLoad" INTEGER NOT NULL DEFAULT 480;

ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "maxCapacity" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "cancellationWindowHours" INTEGER NOT NULL DEFAULT 24;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "allowMembership" BOOLEAN NOT NULL DEFAULT true;
UPDATE "Service" SET "title" = "name" WHERE "title" = '';
